### PR TITLE
Simplify arguments for argparser

### PR DESCRIPTION
**Pull request by zuphilip**
By making source_directory and destination_directory
positional argument they are mandatory but easier
to make a call. Moreover, the check with the other
arugment can be made optional.

### CODE REVIEW

**Comment by doolieSoft** [comment]
Hello,
I tried your suggestion, but I can't manage to make a call with these parameter.
```
PdfPasswordRemoverEnv) C:\Users\c158492\ProjetBoulot\PYTHON\PdfPasswordRemover>python PdfPasswordRemover.py source_directory=C:\Users\c158492\Desktop\NouveauDossier destination_directory=C:\Users\c158492\Desktop\NouveauDossier
Traceback (most recent call last):
  File "PdfPasswordRemover.py", line 115, in <module>
    main()
  File "PdfPasswordRemover.py", line 39, in main
    for file_name in os.listdir(source_directory):
OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte: 'source_directory=C:\\Users\\c158492\\Desktop\\NouveauDossier\\'
```

Can you show me how I can make a call with these positional argument.
thanks,
Stefano

**Comment by zuphilip** [comment]
Just try without the parameters, i.e.
```
>python PdfPasswordRemover.py C:\Users\c158492\Desktop\NouveauDossier C:\Users\c158492\Desktop\NouveauDossier
```
Let me know whether it works and what you think about it.

**Comment by doolieSoft** [comment]
It works well like this. And making the age_of_file_to_treat optional is fine also.
Thank you :)

**Comment by zuphilip** [comment]
Glad you it worked and is okay for you. Happy to contribute!

**Pull request merged**
